# === FUNCTIONALITY SETTINGS ===
POWER_LINE: true # Automatically burns all leftover fuels
DO_NOT_BURN: # If POWER_LINE is true, don't burn these
  - toluene
  - phenol
  - hydrogen
  - creosote oil
  - sulfuric naphtha
  - sulfuric gas
  - sulfuric heavy fuel
  - sulfuric light fuel
  - coal tar oil
  - naphtha
OUTPUT_FORMAT: png # png or pdf (pdf is searchable)
USE_RAINBOW_EDGES: true # feature to help distinguish between overlapping edges
DUR_FORMAT: sec # choose either "ticks" or "sec"
VIEW_ON_COMPLETION: true

# === VISUALS ===
GENERAL_FONT: arial  # nodes and edges
SUMMARY_FONT: arial
GROUP_FONT: verdana
NODE_FONTSIZE: 11
EDGE_FONTSIZE: 10
GROUP_FONTSIZE: 18
BACKGROUND_COLOR: '#043742'
EDGECOLOR_CYCLE:
  - '#b58900' # 'yellow'
  - '#cb4b16' # 'orange'
  - '#dc322f' # 'red'
  - '#d33682' # 'magenta'
  - '#6c71c4' # 'violet'
  - '#268bd2' # 'blue'
  - '#2aa198' # 'cyan'
  - '#859900' # 'green'
SOURCESINK_COLOR: 'ghostwhite'
NONLOCKEDNODE_COLOR: 'lightblue2'
LOCKEDNODE_COLOR: 'green'
POSITIVE_COLOR: '#859900'
NEGATIVE_COLOR: '#dc322f'
ORIENTATION: 'TB'
# TB: Vertical, LR: Horizontal, BT: Vertical Inverted, RL: Horizontal Inverted
# [TB, LR, BT, RL]
LINE_STYLE: 'spline'
# [line, spline, polyline, curved] 
# don't use ortho it's buggy
COMBINE_INPUTS: True
COMBINE_OUTPUTS: True
# Whether to create a new meta node before multi-input/after multi-output ports


# { These settings are not added to backend yet
PRECISION: 4
ROUND_MACHINES_UP: false
# }

# { You should probably only modify these if you are dev
DEBUG_SHOW_EVERY_STEP: false
SHOW_MACHINE_INDICES: false
# }
